sudo: required

language: go

services:
- docker

addons:
  apt:
    packages:
    - docker-ce

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

os:
- linux

go:
# reason for bumping 1.11.x to 1.11.4+ is this: https://github.com/golang/go/issues/30446#issuecomment-468038052
- "1.11.4"
- "1.12"


env:
  global:
    - TM_VERSION=v0.31.5
    - BUILD_VERSION=$(echo ${TRAVIS_COMMIT} | cut -c 1-10)
    - MAIN_GO_VERSION=1.12
    - GORACE="halt_on_error=1"
    - FORCE_TM_TEST=1

install:
- go get -d github.com/tendermint/tendermint/... ;
  cd ${GOPATH}/src/github.com/tendermint/tendermint ;
  git checkout ${TM_VERSION} ;
  make get_tools && make check && make install ;
  cd -;

script:
- make protolint;
- make protodocs;
- make install;
- make all;
- if [[ "$TRAVIS_GO_VERSION" == "$MAIN_GO_VERSION" ]]; then
     make cover;
     ./coverage/upload.sh;
   fi;
- printenv | grep -Ev "PATH|path|GEM" > env.list
- docker run -it --rm --env-file env.list -v "$(pwd):/usr/src/app" iov1ops/danger:latest > danger.out; cat danger.out
- if [[ "$TRAVIS_GO_VERSION" == "$MAIN_GO_VERSION" && "$TRAVIS_OS_NAME" == "linux" ]]; then
    release_latest=$( [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_TAG" == "" && "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]] && echo "yes" || echo "no" );
    release_tag=$( [[ "$TRAVIS_TAG" != "" ]] && echo "yes" || echo "no" );

    if [[ $release_latest == "yes" || $release_tag == "yes" ]]; then
      make dist;
    fi

    if [[ $release_latest == "yes" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker tag  "iov1/bnsd:${BUILD_VERSION}" "iov1/bnsd:latest" ;
      docker push "iov1/bnsd:latest";
      docker logout;
    fi;

    if [[ $release_tag == "yes" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker tag  "iov1/bnsd:${BUILD_VERSION}" "iov1/bnsd:$TRAVIS_TAG" ;
      docker push "iov1/bnsd:$TRAVIS_TAG";
      docker logout;
    fi;
  fi;


notifications:
  email: false

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master
  - launch
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/
